openapi: 3.1.0
info:
  title: Products Service API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://7dh1v6j0jd.execute-api.eu-central-1.amazonaws.com/prod

paths:
  /products:
    get:
      summary: Get list of products
      responses:
        "200":
          description: Returns a list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                sample:
                  summary: A sample list of products
                  value:
                    - id: "1"
                      title: "Sample Product 1"
                      description: "Description for Sample Product 1"
                      price: 99.99
                      count: 10
                    - id: "2"
                      title: "Sample Product 2"
                      description: "Description for Sample Product 2"
                      price: 149.99
                      count: 5
        "404":
          description: No products found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                noProducts:
                  summary: No products found response
                  value:
                    message: "No products found"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                serverError:
                  summary: Server error response
                  value:
                    message: "Could not fetch products"
    post:
      summary: Create a new product
      requestBody:
        description: Product to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProduct"
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              examples:
                sample:
                  summary: A sample product response
                  value:
                    id: "1"
                    title: "Sample Product 1"
                    description: "Description for Sample Product 1"
                    price: 99.99
                    count: 10
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                invalid:
                  summary: Invalid input response
                  value:
                    message: "Invalid input. Title (string), description (string), price (number), and count (integer) are required."
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                serverError:
                  summary: Server error response
                  value:
                    message: "Could not create product"

  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "1"
      responses:
        "200":
          description: A single product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              examples:
                sample:
                  summary: A sample product
                  value:
                    id: "1"
                    title: "Sample Product 1"
                    description: "Description for Sample Product 1"
                    price: 99.99
                    count: 10
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                notFound:
                  summary: Product not found response
                  value:
                    message: "Product not found"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                invalid:
                  summary: Invalid request response
                  value:
                    message: "Invalid product ID"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                serverError:
                  summary: Server error response
                  value:
                    message: "Could not fetch product"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: integer
      example:
        id: "1"
        title: "Sample Product 1"
        description: "Description for Sample Product 1"
        price: 99.99
        count: 10

    NewProduct:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: integer
      required:
        - title
        - description
        - price
        - count
      example:
        title: "Sample Product"
        description: "Description for Sample Product"
        price: 99.99
        count: 10

    Error:
      type: object
      properties:
        message:
          type: string
      example:
        message: "Error message"
